# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergartens', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入教师姓名', max_length=50, verbose_name='教师姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10, verbose_name='性别')),
                ('position', models.CharField(choices=[('headmaster', '园长'), ('deputy_headmaster', '副园长'), ('head_teacher', '班主任'), ('assistant_teacher', '配班老师'), ('life_teacher', '生活老师'), ('principal', '园长'), ('teacher', '教师'), ('assistant', '助教')], default='teacher', max_length=30, verbose_name='职务')),
                ('employee_id', models.CharField(blank=True, help_text='请输入教师工号', max_length=30, null=True, verbose_name='工号')),
                ('phone', models.CharField(blank=True, help_text='请输入教师手机号', max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='电子邮箱')),
                ('id_card', models.CharField(blank=True, help_text='请输入教师身份证号', max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/', verbose_name='教师照片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='classes.class', verbose_name='负责班级')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='kindergartens.kindergarten', verbose_name='所属幼儿园')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
