# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入选区名称，如阅读区、建构区等', max_length=100, verbose_name='选区名称')),
                ('description', models.TextField(blank=True, help_text='选区的详细描述信息', null=True, verbose_name='选区描述')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '选区定义',
                'verbose_name_plural': '选区定义',
                'db_table': 'selection_areas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SelectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='记录日期')),
                ('select_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='选择时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_records', to='children.child', verbose_name='幼儿')),
            ],
            options={
                'verbose_name': '选区记录',
                'verbose_name_plural': '选区记录管理',
                'ordering': ['-date', '-select_time'],
            },
        ),
    ]
