# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('selections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionrecord',
            name='operated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selection_records', to=settings.AUTH_USER_MODEL, verbose_name='操作教师'),
        ),
        migrations.AddField(
            model_name='selectionrecord',
            name='selection_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_records', to='selections.selectionarea', verbose_name='选区'),
        ),
        migrations.AddField(
            model_name='selectionarea',
            name='class_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_areas', to='classes.class', verbose_name='所属班级'),
        ),
        migrations.AlterUniqueTogether(
            name='selectionrecord',
            unique_together={('child', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='selectionarea',
            unique_together={('name', 'class_info')},
        ),
    ]
