# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入幼儿姓名', max_length=50, verbose_name='幼儿姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, help_text='请选择幼儿出生日期', null=True, verbose_name='出生日期')),
                ('student_id', models.CharField(blank=True, help_text='请输入幼儿学号', max_length=20, null=True, unique=True, verbose_name='学号')),
                ('admission_date', models.DateField(blank=True, help_text='请选择幼儿入园日期', null=True, verbose_name='入园日期')),
                ('parent_name', models.CharField(blank=True, help_text='请输入家长姓名', max_length=50, null=True, verbose_name='家长姓名')),
                ('parent_phone', models.CharField(blank=True, help_text='请输入家长手机号', max_length=11, null=True, verbose_name='家长手机号')),
                ('parent_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='家长邮箱')),
                ('home_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='家庭地址')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='child_avatars/', verbose_name='幼儿头像')),
                ('health_notes', models.TextField(blank=True, help_text='过敏史、特殊疾病等健康相关信息', null=True, verbose_name='健康备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在读')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='classes.class', verbose_name='所属班级')),
            ],
            options={
                'verbose_name': '幼儿',
                'verbose_name_plural': '幼儿管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
