# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kindergartens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('class_type', models.CharField(choices=[('nursery', '托儿所'), ('small', '小班'), ('middle', '中班'), ('large', '大班'), ('pre_school', '学前班')], default='small', max_length=20, verbose_name='班级类型')),
                ('classroom_location', models.CharField(blank=True, default='', max_length=100, verbose_name='教室位置')),
                ('description', models.TextField(blank=True, verbose_name='班级描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergartens.kindergarten', verbose_name='所属幼儿园')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['kindergarten', 'name'],
                'unique_together': {('kindergarten', 'name')},
            },
        ),
    ]
