# Generated by Django 4.2.7 on 2025-12-03 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='请输入幼儿园全称', max_length=100, unique=True, verbose_name='幼儿园名称')),
                ('kindergarten_type', models.CharField(choices=[('public', '公立'), ('private', '私立'), ('chain', '连锁')], default='private', max_length=20, verbose_name='园所类型')),
                ('address', models.CharField(blank=True, help_text='请输入幼儿园的详细地址', max_length=255, null=True, verbose_name='详细地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('principal_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='园长姓名')),
                ('region', models.CharField(blank=True, help_text='请输入幼儿园所在地区', max_length=100, null=True, verbose_name='地区')),
                ('total_students', models.IntegerField(default=0, help_text='幼儿园学生总数', verbose_name='学生总数')),
                ('total_classes', models.IntegerField(default=0, help_text='幼儿园班级总数', verbose_name='班级总数')),
                ('total_teachers', models.IntegerField(default=0, help_text='幼儿园教师总数', verbose_name='教师总数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '幼儿园',
                'verbose_name_plural': '幼儿园管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
